name = "parts-inventory"
main = "src/worker/index.ts"
compatibility_date = "2026-06-03"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "parts-inventory"
database_id = "c4e9bc98-2d9e-4e54-b499-8859076c787a"
