name = "parts-inventory"
main = "src/worker/index.ts"
compatibility_date = "2026-06-03"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "db-parts"
database_id = "d60b99ec-c57d-40a4-9646-4e59d6958e23"